services:
    _defaults:
        public: false
    
    helpers_request.helpers_request:
        class: 'Jalismrs\HelpersRequestBundle\HelpersRequest'
        arguments:
            $rateLimitProvider: '@Maba\GentleForce\RateLimitProvider'
            $throttler: '@Maba\GentleForce\ThrottlerInterface'
    
    Jalismrs\HelpersRequestBundle\HelpersRequest: '@helpers_request.helpers_request'
    
    # maba/gentle-force
    Maba\GentleForce\RateLimitProvider:
        autowire: true
    Maba\GentleForce\Throttler:
        arguments:
            $client: '@Predis\Client'
            $rateLimitProvider: '@Maba\GentleForce\RateLimitProvider'
            $prefix: 'rate_limit::'
    Maba\GentleForce\ThrottlerInterface: '@Maba\GentleForce\Throttler'
    
    # predis/predis
    Predis\Client:
        arguments:
            $parameters:
                host: '%env(REDIS_HOST)%'
            $options:
                prefix: '%app.name%::'
